// milestone.service.js
import { prisma } from '../config/prismaClient.js';
import dayjs from 'dayjs';
import { sendMilestoneCompletedMessage } from './roadmapNotification.service.js';
import logger from '../config/logger.js';

/**
 * Create a new milestone
 * @param {number} goalId - Goal ID
 * @param {Object} data - Milestone data
 * @returns {Promise<Object>} - Created milestone
 */
export const createMilestone = async (goalId, data) => {
  const { title, description, dueDate, period, year, quarter, month, estimatedEffortHours, order } = data;

  const milestone = await prisma.milestone.create({
    data: {
      goalId,
      title,
      description,
      dueDate: new Date(dueDate),
      period,
      year,
      quarter,
      month,
      estimatedEffortHours,
      order: order || 0,
      status: 'not_started',
      isAutoGenerated: data.isAutoGenerated || false,
    },
  });

  return milestone;
};

/**
 * Get milestone by ID
 * @param {number} milestoneId - Milestone ID
 * @param {Object} options - Include options
 * @returns {Promise<Object>} - Milestone object
 */
export const getMilestoneById = async (milestoneId, options = {}) => {
  const { includeTasks = false, includeGoal = false } = options;

  const include = {};
  if (includeTasks) {
    include.roadmapTasks = {
      orderBy: { scheduledDate: 'asc' },
    };
  }
  if (includeGoal) {
    include.goal = true;
  }

  const milestone = await prisma.milestone.findUnique({
    where: { id: milestoneId },
    include,
  });

  if (!milestone) {
    throw new Error('Milestone not found');
  }

  return milestone;
};

/**
 * Get all milestones for a goal
 * @param {number} goalId - Goal ID
 * @param {Object} filters - Optional filters
 * @returns {Promise<Array>} - List of milestones
 */
export const getMilestonesForGoal = async (goalId, filters = {}) => {
  const { status, includeTasks = false } = filters;

  const where = { goalId };
  if (status) where.status = status;

  const include = {};
  if (includeTasks) {
    include.roadmapTasks = {
      orderBy: { scheduledDate: 'asc' },
    };
  }

  const milestones = await prisma.milestone.findMany({
    where,
    include,
    orderBy: { order: 'asc' },
  });

  return milestones;
};

/**
 * Get upcoming milestones for a roadmap
 * @param {number} roadmapId - Roadmap ID
 * @param {Object} options - Query options
 * @returns {Promise<Array>} - List of upcoming milestones
 */
export const getUpcomingMilestones = async (roadmapId, options = {}) => {
  const { limit = 5, daysAhead = 30 } = options;

  const today = dayjs();
  const futureDate = today.add(daysAhead, 'day');

  const milestones = await prisma.milestone.findMany({
    where: {
      goal: {
        roadmapId,
      },
      status: {
        in: ['not_started', 'in_progress'],
      },
      dueDate: {
        gte: today.toDate(),
        lte: futureDate.toDate(),
      },
    },
    include: {
      goal: {
        select: {
          id: true,
          title: true,
          category: true,
        },
      },
    },
    orderBy: { dueDate: 'asc' },
    take: limit,
  });

  return milestones;
};

/**
 * Update a milestone
 * @param {number} milestoneId - Milestone ID
 * @param {Object} data - Update data
 * @returns {Promise<Object>} - Updated milestone
 */
export const updateMilestone = async (milestoneId, data) => {
  const milestone = await prisma.milestone.findUnique({
    where: { id: milestoneId },
  });

  if (!milestone) {
    throw new Error('Milestone not found');
  }

  // Convert dueDate to Date if provided
  if (data.dueDate) {
    data.dueDate = new Date(data.dueDate);
  }

  const updated = await prisma.milestone.update({
    where: { id: milestoneId },
    data,
  });

  return updated;
};

/**
 * Delete a milestone
 * @param {number} milestoneId - Milestone ID
 * @returns {Promise<Object>} - Deleted milestone
 */
export const deleteMilestone = async (milestoneId) => {
  const milestone = await prisma.milestone.findUnique({
    where: { id: milestoneId },
  });

  if (!milestone) {
    throw new Error('Milestone not found');
  }

  return await prisma.milestone.delete({
    where: { id: milestoneId },
  });
};

/**
 * Complete a milestone
 * @param {number} milestoneId - Milestone ID
 * @returns {Promise<Object>} - Updated milestone and goal
 */
export const completeMilestone = async (milestoneId) => {
  const milestone = await prisma.milestone.findUnique({
    where: { id: milestoneId },
    include: { goal: true },
  });

  if (!milestone) {
    throw new Error('Milestone not found');
  }

  const updated = await prisma.milestone.update({
    where: { id: milestoneId },
    data: {
      status: 'completed',
      completionDate: new Date(),
    },
  });

  // Send celebration notification (async, don't wait)
  sendMilestoneCompletedMessage(milestoneId).catch((error) => {
    logger.error(`Failed to send milestone completed notification for ${milestoneId}:`, error);
  });

  return updated;
};

/**
 * Check and update overdue milestones
 * @param {number} roadmapId - Roadmap ID (optional, checks all if not provided)
 * @returns {Promise<Array>} - Updated milestones
 */
export const checkOverdueMilestones = async (roadmapId = null) => {
  const where = {
    status: {
      in: ['not_started', 'in_progress'],
    },
    dueDate: {
      lt: new Date(),
    },
  };

  if (roadmapId) {
    where.goal = { roadmapId };
  }

  const overdueMilestones = await prisma.milestone.findMany({
    where,
  });

  const updates = overdueMilestones.map((m) =>
    prisma.milestone.update({
      where: { id: m.id },
      data: { status: 'overdue' },
    })
  );

  return await Promise.all(updates);
};

/**
 * Reorder milestones
 * @param {Array} milestoneOrders - Array of {id, order} objects
 * @returns {Promise<Array>} - Updated milestones
 */
export const reorderMilestones = async (milestoneOrders) => {
  const updates = milestoneOrders.map(({ id, order }) =>
    prisma.milestone.update({
      where: { id },
      data: { order },
    })
  );

  return await Promise.all(updates);
};
