-- CreateEnum
CREATE TYPE "RoadmapStatus" AS ENUM ('draft', 'active', 'paused', 'completed', 'archived');

-- CreateEnum
CREATE TYPE "GenerationMethod" AS ENUM ('llm_assisted', 'manual', 'hybrid');

-- CreateEnum
CREATE TYPE "GoalCategory" AS ENUM ('career', 'health', 'finance', 'relationships', 'learning', 'personal', 'other');

-- CreateEnum
CREATE TYPE "Timeframe" AS ENUM ('year_1', 'year_2', 'year_3', 'year_4', 'year_5', 'ongoing');

-- CreateEnum
CREATE TYPE "GoalStatus" AS ENUM ('not_started', 'in_progress', 'completed', 'blocked', 'abandoned');

-- CreateEnum
CREATE TYPE "MilestoneStatus" AS ENUM ('not_started', 'in_progress', 'completed', 'overdue', 'skipped');

-- CreateEnum
CREATE TYPE "Period" AS ENUM ('Q1', 'Q2', 'Q3', 'Q4', 'monthly');

-- CreateEnum
CREATE TYPE "RoadmapTaskPriority" AS ENUM ('low', 'normal', 'high', 'critical');

-- CreateEnum
CREATE TYPE "RoadmapTaskStatus" AS ENUM ('pending', 'in_progress', 'completed', 'cancelled', 'rescheduled');

-- CreateEnum
CREATE TYPE "TaskSource" AS ENUM ('ai_generated', 'user_created', 'system_suggested');

-- CreateEnum
CREATE TYPE "SnapshotType" AS ENUM ('daily', 'weekly', 'monthly', 'quarterly');

-- CreateEnum
CREATE TYPE "TrendDirection" AS ENUM ('improving', 'stable', 'declining');

-- CreateEnum
CREATE TYPE "AdjustmentTrigger" AS ENUM ('user_requested', 'system_detected', 'scheduled_review');

-- CreateEnum
CREATE TYPE "ReminderType" AS ENUM ('daily_tasks', 'milestone_due', 'weekly_review', 'monthly_review');

-- CreateEnum
CREATE TYPE "ReminderFrequency" AS ENUM ('daily', 'weekly', 'monthly', 'once');

-- CreateEnum
CREATE TYPE "ReminderChannel" AS ENUM ('telegram', 'email', 'both');

-- CreateEnum
CREATE TYPE "MotivationStyle" AS ENUM ('intrinsic', 'extrinsic', 'mixed');

-- CreateEnum
CREATE TYPE "RiskTolerance" AS ENUM ('low', 'medium', 'high');

-- CreateEnum
CREATE TYPE "WorkStyle" AS ENUM ('structured', 'flexible', 'adaptive');

-- CreateTable
CREATE TABLE "PersonalityProfile" (
    "id" SERIAL NOT NULL,
    "userId" INTEGER NOT NULL,
    "mbtiType" TEXT,
    "strengths" JSONB,
    "weaknesses" JSONB,
    "values" JSONB,
    "motivationStyle" "MotivationStyle" NOT NULL DEFAULT 'intrinsic',
    "riskTolerance" "RiskTolerance" NOT NULL DEFAULT 'medium',
    "workStyle" "WorkStyle" NOT NULL DEFAULT 'flexible',
    "assessmentDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "PersonalityProfile_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Roadmap" (
    "id" SERIAL NOT NULL,
    "userId" INTEGER NOT NULL,
    "title" TEXT NOT NULL,
    "visionStatement" TEXT,
    "startDate" TIMESTAMP(3) NOT NULL,
    "endDate" TIMESTAMP(3) NOT NULL,
    "status" "RoadmapStatus" NOT NULL DEFAULT 'draft',
    "generationMethod" "GenerationMethod" NOT NULL DEFAULT 'manual',
    "llmModel" TEXT,
    "generationPrompt" TEXT,
    "lastReviewDate" TIMESTAMP(3),
    "progressPercentage" DECIMAL(5,2) NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Roadmap_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Goal" (
    "id" SERIAL NOT NULL,
    "roadmapId" INTEGER NOT NULL,
    "category" "GoalCategory" NOT NULL,
    "title" TEXT NOT NULL,
    "description" TEXT,
    "priority" INTEGER NOT NULL DEFAULT 3,
    "timeframe" "Timeframe" NOT NULL DEFAULT 'year_1',
    "targetYear" INTEGER NOT NULL,
    "successCriteria" TEXT,
    "dependencies" JSONB,
    "status" "GoalStatus" NOT NULL DEFAULT 'not_started',
    "completionPercentage" DECIMAL(5,2) NOT NULL DEFAULT 0,
    "order" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Goal_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Milestone" (
    "id" SERIAL NOT NULL,
    "goalId" INTEGER NOT NULL,
    "title" TEXT NOT NULL,
    "description" TEXT,
    "dueDate" TIMESTAMP(3) NOT NULL,
    "period" "Period",
    "year" INTEGER NOT NULL,
    "quarter" INTEGER,
    "month" INTEGER,
    "status" "MilestoneStatus" NOT NULL DEFAULT 'not_started',
    "completionDate" TIMESTAMP(3),
    "estimatedEffortHours" INTEGER,
    "actualEffortHours" INTEGER,
    "order" INTEGER NOT NULL DEFAULT 0,
    "isAutoGenerated" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Milestone_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "RoadmapTask" (
    "id" SERIAL NOT NULL,
    "milestoneId" INTEGER,
    "roadmapId" INTEGER NOT NULL,
    "taskId" INTEGER,
    "title" TEXT NOT NULL,
    "description" TEXT,
    "scheduledDate" TIMESTAMP(3) NOT NULL,
    "estimatedDuration" INTEGER,
    "priority" "RoadmapTaskPriority" NOT NULL DEFAULT 'normal',
    "status" "RoadmapTaskStatus" NOT NULL DEFAULT 'pending',
    "completionDate" TIMESTAMP(3),
    "isRecurring" BOOLEAN NOT NULL DEFAULT false,
    "recurrenceRule" TEXT,
    "source" "TaskSource" NOT NULL DEFAULT 'user_created',
    "aiGenerationContext" JSONB,
    "rescheduleCount" INTEGER NOT NULL DEFAULT 0,
    "skipReason" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "RoadmapTask_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ProgressSnapshot" (
    "id" SERIAL NOT NULL,
    "roadmapId" INTEGER NOT NULL,
    "snapshotDate" TIMESTAMP(3) NOT NULL,
    "snapshotType" "SnapshotType" NOT NULL,
    "overallProgress" DECIMAL(5,2) NOT NULL,
    "goalsStarted" INTEGER NOT NULL DEFAULT 0,
    "goalsCompleted" INTEGER NOT NULL DEFAULT 0,
    "milestonesCompleted" INTEGER NOT NULL DEFAULT 0,
    "tasksCompleted" INTEGER NOT NULL DEFAULT 0,
    "tasksSkipped" INTEGER NOT NULL DEFAULT 0,
    "totalFocusMinutes" INTEGER NOT NULL DEFAULT 0,
    "velocityScore" DECIMAL(5,2),
    "trendDirection" "TrendDirection" NOT NULL DEFAULT 'stable',
    "notes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ProgressSnapshot_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "RoadmapAdjustment" (
    "id" SERIAL NOT NULL,
    "roadmapId" INTEGER NOT NULL,
    "adjustmentDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "trigger" "AdjustmentTrigger" NOT NULL,
    "reason" TEXT,
    "affectedGoals" JSONB,
    "affectedMilestones" JSONB,
    "changesSummary" TEXT,
    "llmInvolved" BOOLEAN NOT NULL DEFAULT false,
    "approvedBy" INTEGER,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "RoadmapAdjustment_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "RoadmapReminder" (
    "id" SERIAL NOT NULL,
    "userId" INTEGER NOT NULL,
    "roadmapId" INTEGER NOT NULL,
    "milestoneId" INTEGER,
    "reminderType" "ReminderType" NOT NULL,
    "scheduledTime" TEXT NOT NULL,
    "frequency" "ReminderFrequency" NOT NULL DEFAULT 'daily',
    "nextTrigger" TIMESTAMP(3),
    "channel" "ReminderChannel" NOT NULL DEFAULT 'telegram',
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "lastSent" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "RoadmapReminder_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "PersonalityProfile_userId_key" ON "PersonalityProfile"("userId");

-- CreateIndex
CREATE INDEX "Roadmap_userId_idx" ON "Roadmap"("userId");

-- CreateIndex
CREATE INDEX "Roadmap_userId_status_idx" ON "Roadmap"("userId", "status");

-- CreateIndex
CREATE INDEX "Roadmap_userId_createdAt_idx" ON "Roadmap"("userId", "createdAt");

-- CreateIndex
CREATE INDEX "Goal_roadmapId_idx" ON "Goal"("roadmapId");

-- CreateIndex
CREATE INDEX "Goal_roadmapId_status_idx" ON "Goal"("roadmapId", "status");

-- CreateIndex
CREATE INDEX "Goal_roadmapId_category_idx" ON "Goal"("roadmapId", "category");

-- CreateIndex
CREATE INDEX "Milestone_goalId_idx" ON "Milestone"("goalId");

-- CreateIndex
CREATE INDEX "Milestone_goalId_status_idx" ON "Milestone"("goalId", "status");

-- CreateIndex
CREATE INDEX "Milestone_dueDate_idx" ON "Milestone"("dueDate");

-- CreateIndex
CREATE INDEX "Milestone_status_dueDate_idx" ON "Milestone"("status", "dueDate");

-- CreateIndex
CREATE INDEX "RoadmapTask_roadmapId_idx" ON "RoadmapTask"("roadmapId");

-- CreateIndex
CREATE INDEX "RoadmapTask_milestoneId_idx" ON "RoadmapTask"("milestoneId");

-- CreateIndex
CREATE INDEX "RoadmapTask_roadmapId_status_idx" ON "RoadmapTask"("roadmapId", "status");

-- CreateIndex
CREATE INDEX "RoadmapTask_roadmapId_scheduledDate_idx" ON "RoadmapTask"("roadmapId", "scheduledDate");

-- CreateIndex
CREATE INDEX "RoadmapTask_status_scheduledDate_idx" ON "RoadmapTask"("status", "scheduledDate");

-- CreateIndex
CREATE INDEX "ProgressSnapshot_roadmapId_idx" ON "ProgressSnapshot"("roadmapId");

-- CreateIndex
CREATE INDEX "ProgressSnapshot_roadmapId_snapshotDate_idx" ON "ProgressSnapshot"("roadmapId", "snapshotDate");

-- CreateIndex
CREATE INDEX "ProgressSnapshot_snapshotType_snapshotDate_idx" ON "ProgressSnapshot"("snapshotType", "snapshotDate");

-- CreateIndex
CREATE INDEX "RoadmapAdjustment_roadmapId_idx" ON "RoadmapAdjustment"("roadmapId");

-- CreateIndex
CREATE INDEX "RoadmapAdjustment_roadmapId_adjustmentDate_idx" ON "RoadmapAdjustment"("roadmapId", "adjustmentDate");

-- CreateIndex
CREATE INDEX "RoadmapReminder_userId_idx" ON "RoadmapReminder"("userId");

-- CreateIndex
CREATE INDEX "RoadmapReminder_roadmapId_idx" ON "RoadmapReminder"("roadmapId");

-- CreateIndex
CREATE INDEX "RoadmapReminder_userId_isActive_idx" ON "RoadmapReminder"("userId", "isActive");

-- CreateIndex
CREATE INDEX "RoadmapReminder_nextTrigger_isActive_idx" ON "RoadmapReminder"("nextTrigger", "isActive");

-- AddForeignKey
ALTER TABLE "PersonalityProfile" ADD CONSTRAINT "PersonalityProfile_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Roadmap" ADD CONSTRAINT "Roadmap_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Goal" ADD CONSTRAINT "Goal_roadmapId_fkey" FOREIGN KEY ("roadmapId") REFERENCES "Roadmap"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Milestone" ADD CONSTRAINT "Milestone_goalId_fkey" FOREIGN KEY ("goalId") REFERENCES "Goal"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RoadmapTask" ADD CONSTRAINT "RoadmapTask_milestoneId_fkey" FOREIGN KEY ("milestoneId") REFERENCES "Milestone"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RoadmapTask" ADD CONSTRAINT "RoadmapTask_roadmapId_fkey" FOREIGN KEY ("roadmapId") REFERENCES "Roadmap"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RoadmapTask" ADD CONSTRAINT "RoadmapTask_taskId_fkey" FOREIGN KEY ("taskId") REFERENCES "Task"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ProgressSnapshot" ADD CONSTRAINT "ProgressSnapshot_roadmapId_fkey" FOREIGN KEY ("roadmapId") REFERENCES "Roadmap"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RoadmapAdjustment" ADD CONSTRAINT "RoadmapAdjustment_roadmapId_fkey" FOREIGN KEY ("roadmapId") REFERENCES "Roadmap"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RoadmapReminder" ADD CONSTRAINT "RoadmapReminder_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RoadmapReminder" ADD CONSTRAINT "RoadmapReminder_roadmapId_fkey" FOREIGN KEY ("roadmapId") REFERENCES "Roadmap"("id") ON DELETE CASCADE ON UPDATE CASCADE;
